### ISSUE TITLE
what's  the format of the inferred txts?

### ISSUE THREAD

**Issue by jamiechoi1995** [Haoning724/obbstacking#1]
```
result_root_dir/
├── model_1_test/
│   └── test/
│       ├── Task1_baseball-diamond.txt
```
In my understanding, Task1_baseball-diamond.txt is the inferred result of model_1, but I don't know what's the required format.

The format of DOTA is
```
x1, y1, x2, y2, x3, y3, x4, y4, category, difficult
```
and is different from the format in your code:
https://github.com/Haoning724/obbstacking/blob/7e556128b9eda3c0f379aae7b5b47e4c01c0548b/txt_processor.py#L17-L23

the format in your code looks like:
```
img_name, prob, x1, y1, x2, y2, x3, y3, x4, y4
```
but there are only 10 elements, and your code requires 12 elements.

**Comment by Haoning724** [comment]
This is a late reply but for others that are still in confusion, please check https://captain-whu.github.io/DOTA/tasks.html for the format. Beware the difference between the annotation format and the submission format.
